### ISSUE TITLE
Where is set() called?

### ISSUE THREAD

**Issue by brandondurham** [dbroadhurst/aws-cognito-promises#2]
In your [config file](https://github.com/dbroadhurst/aws-cognito-promises/blob/a23c08f5b0a5002b52b496d245d2bcb7cb86bd74/src/config.js) you have a `set()` function that runs some setup. Where/when is that called?

**Comment by dbroadhurst** [comment]
Look in the reference app

https://github.com/dbroadhurst/aws-cognito-react
https://github.com/dbroadhurst/aws-cognito-react/blob/master/src/components/Auth/Auth.js

**Comment by brandondurham** [comment]
Perfect. Thank you!
